name: Deploy service for Bells Testnet

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Deploy]

jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.BELLS_TESTNET_HOST_1 }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.BELLS_TESTNET_HOST_1 }}
        username: ${{ secrets.BELLS_TESTNET_HOST_1_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/bells-testnet/
          docker compose up -d --force-recreate bells-testnet-indexer